"""Table A/C + Figure A for the open-LLM suite (from consistent metrics)."""
from __future__ import annotations
import csv, json, sys
from pathlib import Path
import numpy as np
REPO=Path(__file__).resolve().parents[1]
TD=REPO/"results/open_llm_suite/tables"; TD.mkdir(parents=True,exist_ok=True)
FD=REPO/"figures/open_llm_suite"; FD.mkdir(parents=True,exist_ok=True)
rng=np.random.default_rng(0)

def seed_bootstrap(d, n=10000):
    d=np.asarray(d,float)
    if len(d)==0: return (np.nan,np.nan,np.nan)
    bs=np.array([rng.choice(d,len(d),replace=True).mean() for _ in range(n)])
    return float(d.mean()), float(np.percentile(bs,2.5)), float(np.percentile(bs,97.5))

# ---- new models (consistent) ----
rows=list(csv.DictReader(open(REPO/"results/open_llm_suite/raw/metrics_from_features_full.csv")))
def val(model,init,k,seed):
    for r in rows:
        if r["model"]==model and r["init"]==init and r["seed"]==str(seed) and r.get(k): return float(r[k])
    return None
new_models=["gemma2_2b","gemma2_9b","llama32_3b"]
tableA=[]

# Qwen3-8B from v2 per-window audit (paired bootstrap on bal3)
pb=json.loads((REPO/"results/iclr/tsfm_deliver_v2/audit/paired_bootstrap.json").read_text())["C_routing"]["qwen3_8b_base"]["bal3"]
tableA.append(dict(model="Qwen3-8B",params="8.0B",hidden=4096,clean_P=0.981,clean_R=0.900,
                   readout_P=0.588,readout_R=0.679,ood_P=0.833,ood_R=0.522,delta=0.311,
                   ci_lo=pb["ba_delta_ci95"][0],ci_hi=pb["ba_delta_ci95"][1],routed_P=0.710,routed_R=1.395))
PARAMS={"gemma2_2b":("2.6B",2304),"gemma2_9b":("9.2B",3584),"llama32_3b":("3.2B",3072)}
for m in new_models:
    ds=[]
    for s in [7,17,27]:
        p=val(m,"pretrained","C_family_bal3",s); r=val(m,"random","C_family_bal3",s)
        if p is not None and r is not None: ds.append(p-r)
    mean,lo,hi=seed_bootstrap(ds)
    pr=np.mean([val(m,"pretrained","C_family_bal3",s) for s in [7,17,27]])
    rr=np.mean([val(m,"random","C_family_bal3",s) for s in [7,17,27]])
    rp=np.mean([val(m,"pretrained","R_mlp_bal3",s) for s in [7,17,27]])
    rrun=np.mean([val(m,"random","R_mlp_bal3",s) for s in [7,17,27]])
    tableA.append(dict(model={"gemma2_2b":"Gemma-2-2B","gemma2_9b":"Gemma-2-9B","llama32_3b":"Llama-3.2-3B"}[m],
        params=PARAMS[m][0],hidden=PARAMS[m][1],
        clean_P=np.mean([val(m,"pretrained","A_recog",s) for s in [7,17,27]]),
        clean_R=np.mean([val(m,"random","A_recog",s) for s in [7,17,27]]),
        readout_P=np.mean([val(m,"pretrained","B_linear",s) for s in [7,17,27]]),
        readout_R=np.mean([val(m,"random","B_linear",s) for s in [7,17,27]]),
        ood_P=pr,ood_R=rr,delta=mean,ci_lo=lo,ci_hi=hi,routed_P=rp,routed_R=rrun))
with open(TD/"tableA_openllm.csv","w",newline="") as f:
    w=csv.DictWriter(f,fieldnames=list(tableA[0].keys())); w.writeheader()
    for r in tableA: w.writerow({k:(round(v,4) if isinstance(v,float) else v) for k,v in r.items()})
print("wrote tableA_openllm.csv")
for r in tableA:
    print(f"{r['model']:<14} clean {r['clean_P']:.3f}/{r['clean_R']:.3f}  readout {r['readout_P']:.3f}/{r['readout_R']:.3f}  OOD {r['ood_P']:.3f}/{r['ood_R']:.3f}  delta {r['delta']:+.3f} [{r['ci_lo']:+.3f},{r['ci_hi']:+.3f}]")

# ---- forest plot: open LMs + TSFMs ----
tsfm=json.loads((REPO/"results/iclr/tsfm_deliver_v2/audit/paired_bootstrap.json").read_text())["C_routing"]
items=[]
for r in tableA:
    items.append((r["model"], r["delta"], r["ci_lo"], r["ci_hi"], "LM"))
for m in ["chronos_t5-base","chronos_t5-small","chronos_bolt-small","timesfm_2.5-200m","moment-1-large","moirai-1.1-R-small"]:
    d=tsfm[m]["bal3"]; items.append((m.replace("_"," "), d["ba_delta_mean_over_seeds"], d["ba_delta_ci95"][0], d["ba_delta_ci95"][1], "TSFM"))
try:
    import matplotlib; matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    fig,ax=plt.subplots(figsize=(7.2,4.6))
    items_sorted=sorted(items,key=lambda x:x[1])
    y=np.arange(len(items_sorted))
    for i,(name,d,lo,hi,fam) in enumerate(items_sorted):
        col="#1f77b4" if fam=="LM" else "#d62728"
        ax.plot([lo,hi],[i,i],color=col,lw=1.8)
        ax.plot([d],[i],marker="o",color=col,ms=5)
    ax.axvline(0,color="gray",ls="--",lw=1)
    ax.set_yticks(y); ax.set_yticklabels([f"{n} ({f})" for n,_,_,_,f in items_sorted],fontsize=8)
    ax.set_xlabel("Pretrained - Random OOD balanced accuracy (family-label, bal3)")
    ax.set_xlim(-0.35,0.45)
    ax.set_title("Compositional-transfer gain: open LMs vs time-series foundation models",fontsize=9)
    fig.tight_layout(); fig.savefig(FD/"figA_forest.png",dpi=200); fig.savefig(FD/"figA_forest.pdf")
    print("wrote figA_forest.png/pdf")
except Exception as e:
    print("figure failed:",e)
# latex for table A
with open(TD/"tableA_openllm.tex","w") as f:
    f.write("% auto-generated by scripts/openllm_tables.py\n\\begin{tabular}{lrrrrrr}\n\\toprule\nModel & Params & Clean P/R & Readout P/R & OOD P/R & $\\Delta$ & 95\\% CI \\\\\n\\midrule\n")
    for r in tableA:
        f.write(f"{r['model']} & {r['params']} & {r['clean_P']:.3f}/{r['clean_R']:.3f} & {r['readout_P']:.3f}/{r['readout_R']:.3f} & {r['ood_P']:.3f}/{r['ood_R']:.3f} & {r['delta']:+.3f} & [{r['ci_lo']:+.3f},{r['ci_hi']:+.3f}] \\\\\n")
    f.write("\\bottomrule\n\\end{tabular}\n")
print("wrote tableA_openllm.tex")
